### ISSUE TITLE
有考虑改成 swift 项目么

### ISSUE THREAD

**Issue by WBinBin001** [chenxing640/QPlayer#1]
现在使用 oc 的项目很少了吧，如果改成 swift 应该更好一点。

**Comment by itenfay** [comment]
可以考虑

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月26日 18:32 |
| 收件人 | chenxing640/QPlayer ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [chenxing640/QPlayer] 有考虑改成 swift 项目么 (Issue #1) |

现在使用 oc 的项目很少了吧，如果改成 swift 应该更好一点。
